### PR TITLE
Feature : chroot for RHEL7/CentOS7

### PR DESCRIPTION
**Pull request by cedef**
Here is the proposed implementation of the chroot feature.
For now, it only works for RHEL7/CentOS7.

This branch *includes* both lint (PR #123 ) and feat/spec (PR #124) branches so you can merge everything at once.

### CODE REVIEW

**Comment by inkblot** [comment]
I take issue with your characterization that "for now" it only works on RedHat derivatives. The strategy used in RedHat (a separate `bind-chroot` package) cannot translate to Debian because no similar package exists on Debian, whereas the strategy used on Debian (step-by-step configuration of standard packages) can translate to RedHat. Therefore this implementation is not merely limited to RedHat "for now," but rather it is guaranteed to only ever work on RedHat derived distributions.

I have merged your changes up to `9d640d64` but I will not merge this chroot implementation.

**Comment by cedef** [comment]
Ok, I understand your point of view and quite agree about my patch which is "RedHat-oriented".
I think the best way would be to follow each distribution philosophy.

What would you think of an implementation that:
- use RedHat chroot package on redhat
- follow debian steps on Debian

Hieradata/parameters would be as much as possible *identical* between both solutions with *some specific parameters* for each.

Would that be ok for you ?

**Comment by inkblot** [comment]
I guess it depends on how that's done. I think I could accept a polymorphic model that completely separates the two strategies. I'm thinking of some code I wrote in [puppet-serf](/inkblot/puppet-serf) to handle initscript vs upstart vs systemd service definitions.

In the `bind` class a similar structure for chroot would look something like:

```
if $chroot and $::bind::defaults::chroot_class {
  class { $::bind::defaults::chroot_class:
    # The parameters here need to be standardized across all of the chroot strategy
    # classes. Think of them as subclasses of a base class that doesn't really exist (or
    # need to exist)
  }
} elsif $chroot {
  fail('There is no chroot strategy for your platform')
} else {
  # Is there an else case? I don't know if there needs to be an else case
}
```

And then the `chroot_class` would come from hiera module data based on os family, name, and if necessary, version.

**Comment by cedef** [comment]
I've finally found some time to implement what we've talked about.

Here is a first *draft* on my [forked repo](https://github.com/cedef/puppet-bind/tree/feat/chroot). Before going further, I'd like to get your feedback on the following points:

- code has been splitted into `bind::chroot::package` (for RHEL) and `bind::chroot::manual` (for Debian and probably any other distro).

- I'm not sure how the Debian way should translate into Puppet idem-potency: the `/etc/bind` directory points to `/var/bind9/chroot/etc/bind`, so I've used an `exec` resource to move the `/etc/bind` dir and then I declare a symlink. This way I don't need to change _all_ paths already declared into your code (`/etc/bind/named.conf`, `/etc/bind/**`, ..) as it will pass through the symlink _transparently_.

Note: this draft _does not work on Debian for now_, due to an ordering error between `/etc/bind` dir creation, symlinking and moving.

Regards,

**Pull request closed without merging**
