### PR TITLE
Implement support for logging configuration

### PR DESCRIPTION
**Pull request by inkblot**
Adds `bind::logging::channel` and `bind::logging::category` defines in order to
support logging configuration.

### CODE REVIEW

**Comment by makeacode** [comment]
I completely agree that your implementation is much better.  Thanks for putting in the time on the new PR.

**Comment by inkblot** [comment]
These are the defines that I added to my server configuration to check my work:

```
    bind::logging::channel { 'querylog':
        destination => 'file',
        file_name   => 'query.log',
    }
    bind::logging::category { 'queries':
        channels => 'querylog',
    }
    bind::logging::category { [
        'lame-servers',
        'edns-disabled',
        ]:
        channels => 'null',
    }
```

**Comment by WetHippie** [comment]
That looks great.

**Comment by inkblot** [comment]
This change is included in version 7.2.0 of the module on the forge.

**Pull request merged**
