### PR TITLE
Add option to filter ipv6 address on ipv4

### PR DESCRIPTION
**Pull request by jfroche**
refs https://kb.isc.org/article/AA-00576/0/Filter-AAAA-option-in-BIND-9-.html

### CODE REVIEW

**Comment by roidelapluie** [comment]
needs rebase

**Comment by inkblot** [comment]
I have rebased this branch onto master and merged the rebased branch.

**Comment by inkblot** [comment]
I have also merged it into the `6.0-prerelease` branch

**Comment by inkblot** [comment]
I have released version 5.2.0 of the module to the Puppet Forge which includes this PR.

**Pull request closed without merging**
